apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: costra-ingress
  namespace: costra
  labels:
    app: costra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: costra-compress@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - costra.app
      secretName: costra-tls
  rules:
    - host: costra.app
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: costra-backend
                port:
                  number: 3002
          - path: /
            pathType: Prefix
            backend:
              service:
                name: costra-frontend
                port:
                  number: 8080
